numberOfDays = int( input( "How many days of scores? " ))
day1 = int( input( "Enter the score for day 1: " )) 
day2 = int( input( "Enter the score for day 2: " )) 
day3 = int( input( "Enter the score for day 3: " )) 
day4 = int( input( "Enter the score for day 4: " ))
totalScore = float(day1 + day2 + day3 + day4) 
print("The total score of the", numberOfDays, "days is ", totalScore)
